name: Wagtail Localize Git CI

on:
  push:
    branches:
      - main
      - 'stable/**'

  pull_request:

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
        django: ['2.2', '3.1']
        wagtail: ['2.11', '2.12', '2.13', '2.14']
        exclude:
          # Exclude tests of Django 2.2 and Wagtail 2.14 together
          - django: '2.2'
            wagtail: '2.14'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8']
        django: ['2.2', '3.1']
        wagtail: ['2.11', '2.12', '2.13', '2.14']
        postgres: ['10.8']
        include:
          - python: '3.8'
            django: '3.2'
            wagtail: '2.13'
          - python: '3.8'
            django: '3.2'
            wagtail: '2.15'
            postgres: '10.8'
        exclude:
          # Exclude tests of Django 2.2 and Wagtail 2.14 together
          - django: '2.2'
            wagtail: '2.14'

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/wagtail_localize_git
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-postgres
